### ISSUE TITLE
Selecting an item from multiple search results doesn't update the parameter in DialogFlow

### ISSUE THREAD

**Issue by anubhavmisra** [anubhavmisra/bot-api#1]
Steps to reproduce

1. Order 'Bru Coffee'
2. API returns multiple results.
3. Send back a number(Example: 2)
4. Product is added. 

Post:
The 'product' parameter still shows 'Bru Coffee'

**Comment by jbors** [comment]
Added the updated product to the 'contextOut' for context 'orderintent-followup'. With proper configuration of reading the 'product' parameter in the intent, the value should be updated
